import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav"
import { Sidebar } from '../components/ui/sidebar';
import { playlists } from "@/data/playlists";
import { Menu } from "@/components/menu";
import Header from "@/components/header";
import { SiteHeader } from "@/components/nav/site-header"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
      <SiteHeader />
      {children}
      </body>
    </html>
  );
}
